### ISSUE TITLE
Using transmog items causes the worldserver process to stop.

### ISSUE THREAD

**Issue by jamssismy** [azerothcore/mod-transmog#194]
"This error occurred today after I updated my server code. The update time was February 3, 2025.

My actions:
1.Used the command git pull origin master to fetch the latest AzerothCore code.
2.Reinstalled [mod-eluna](https://github.com/azerothcore/mod-eluna) 
3.Reinstalled [mod-transmog](https://github.com/azerothcore/mod-transmog)
4.Reinstalled [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
5.Reinstalled [mod-congrats-on-level](https://github.com/azerothcore/mod-congrats-on-level)
6.Reinstalled [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)

After rebuilding and installing the code, I started the authentication server and the world server, then logged into the game using a GM account to test the transmog module.

If you need me to provide any additional information, please let me know.

**Comment by jamssismy** [comment]
I reinstalled a previous version of the transmog module, but the server still stops running. This suggests that the issue is not caused by the transmog module itself, but rather a conflict with other updates. I’m not sure which specific module or code is causing the problem, but I am currently testing it.

**Comment by saligin** [comment]
I confirm, the exact same error occurs! When interacting with an NPC, the server crashes with Segmentation fault (core dumped).

**Comment by IvanLlanas** [comment]
I'm getting "Segmentation fault (core dumped)" error too but the very moment I (try to) make or remove a transmogrification. The interaction with the NPC is ok.
I tried to reproduce the error with clean databases but (even looting few armor pieces and weapons) the NPC did not show any available pieces as options.

**Comment by jamssismy** [comment]
After the recent update, many mods have encountered issues—not just the transmog mod. In my testing, mods like mod-item-level-up and mod-ah-bot also had problems.

I tried to submit a report in the AzerothCore work discussion forum, but I am not sure how to format it correctly. I hope you can help me report these issues, including problems with the transmog mod, auction house mod, and level-up mod.

This is quite a serious issue, as it makes users hesitant to update. If these problems occur after an update, they will affect all players on the server.

In my opinion, this is likely an issue with the core code. Logically speaking, if it were just a problem with the mods, it wouldn’t cause other mods to stop working or lead to the world server crashing. This issue was probably caused by recent changes to the AzerothCore work core code.

Please help with this! I would really appreciate it.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/21327 will fix this crash once its merged and probably all others

**Comment by jamssismy** [comment]
Reinstalled mod-ah-bot  mod-item-level-up ， These two mods have even more serious issues—after installation, the world server fails to run completely.

**Comment by jamssismy** [comment]
Thank you very much!

**Comment by sudlud** [comment]
should be fixed with the linked core PR

**Comment by ddrollinger914** [comment]
I've updated the mod with the fix and we're still experiencing this issue on our server. Our core has been updated to whatever the latest master is.

**Comment by Nyeriah** [comment]
We can't help you without a crash log to know what is crashing it

**Comment by ddrollinger914** [comment]
Sorry, it was my fault. I purged my build folder and rebuilt everything, working like a dream now!
